# Generated by Django 6.0.6 on 2026-06-28 10:04

import shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.utils.product_image_path),
        ),
    ]
