# Generated by Django 6.0.6 on 2026-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_created_at_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
